In [3]:
import os
import pandas as pd

In [13]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\anaconda3\envs\geom2005\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\anaconda3\envs\geom2005\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
os.chdir("C:\\Users\\joshs\\OneDrive\\Desktop\\GEOM4009\\Group project\\")

os.listdir()

['aggregated_stats.xls',
 'GEDI02_A_002-20260210_184841',
 'GEDI_DATA.py',
 'Group Project Gannt Chart.xlsx',
 'PolygonPeat2',
 'Test']

In [25]:
df = pd.read_csv("aggregated_stats.xls")
df

,polygon_id,h_canopy_mean,h_canopy_min,h_canopy_max,h_canopy_std,satellite,elevation_mean,elevation_min,elevation_max,elevation_std,canopy_h_mean,canopy_h_min,canopy_h_max,canopy_h_std
0,3,3.402823e+38,3.402823e+38,3.402823e+38,0.000000e+00,ICESat-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,1.361129e+38,4.332809e+00,3.402823e+38,1.725546e+38,ICESat-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,NaN,NaN,NaN,NaN,GEDI,244.631805,244.60385,244.65976,0.039534,2.80000,2.65,2.95,0.212132
3,2,NaN,NaN,NaN,NaN,GEDI,621.499291,243.98901,4765.62600,1276.288660,4.14875,2.32,23.24,4.477764
4,3,NaN,NaN,NaN,NaN,GEDI,244.474685,244.06517,245.05518,0.447763,2.54875,2.24,2.69,0.147012
5,4,NaN,NaN,NaN,NaN,GEDI,243.441815,243.28610,243.79149,0.235260,2.81500,2.58,3.07,0.250932

In [26]:
# cmb means combined canopy height data for GEDI and ICESat
df["cmb_mean"] = df["h_canopy_mean"].combine_first(df["canopy_h_mean"])
df["cmb_min"] = df["h_canopy_min"].combine_first(df["canopy_h_mean"])
df["cmb_max"] = df["h_canopy_max"].combine_first(df["canopy_h_max"])
df["cmb_std"] = df["h_canopy_std"].combine_first(df["canopy_h_std"])
df

,polygon_id,h_canopy_mean,h_canopy_min,h_canopy_max,h_canopy_std,satellite,elevation_mean,elevation_min,elevation_max,elevation_std,canopy_h_mean,canopy_h_min,canopy_h_max,canopy_h_std,cmb_mean,cmb_min,cmb_max,cmb_std
0,3,3.402823e+38,3.402823e+38,3.402823e+38,0.000000e+00,ICESat-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.402823e+38,3.402823e+38,3.402823e+38,0.000000e+00
1,4,1.361129e+38,4.332809e+00,3.402823e+38,1.725546e+38,ICESat-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.361129e+38,4.332809e+00,3.402823e+38,1.725546e+38
2,1,NaN,NaN,NaN,NaN,GEDI,244.631805,244.60385,244.65976,0.039534,2.80000,2.65,2.95,0.212132,2.800000e+00,2.800000e+00,2.950000e+00,2.121320e-01
3,2,NaN,NaN,NaN,NaN,GEDI,621.499291,243.98901,4765.62600,1276.288660,4.14875,2.32,23.24,4.477764,4.148750e+00,4.148750e+00,2.324000e+01,4.477764e+00
4,3,NaN,NaN,NaN,NaN,GEDI,244.474685,244.06517,245.05518,0.447763,2.54875,2.24,2.69,0.147012,2.548750e+00,2.548750e+00,2.690000e+00,1.470119e-01
5,4,NaN,NaN,NaN,NaN,GEDI,243.441815,243.28610,243.79149,0.235260,2.81500,2.58,3.07,0.250932,2.815000e+00,2.815000e+00,3.070000e+00,2.509316e-01

In [38]:
# Calculate difference for canopy height mean, max, min, std. Concatenate into one dataframe
mean_diff = df.groupby("polygon_id")["cmb_mean"].apply(lambda x: x.max() - x.min())
max_diff = df.groupby("polygon_id")["cmb_max"].apply(lambda x: x.max() - x.min())
min_diff = df.groupby("polygon_id")["cmb_min"].apply(lambda x: x.max() - x.min())
std_diff = df.groupby("polygon_id")["cmb_std"].apply(lambda x: x.max() - x.min())
final_df = pd.concat([mean_diff, max_diff, min_diff, std_diff], axis=1)
final_df

                cmb_mean       cmb_max       cmb_min       cmb_std
polygon_id
1           0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
2           0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
3           3.402823e+38  3.402823e+38  3.402823e+38  1.470119e-01
4           1.361129e+38  3.402823e+38  1.517809e+00  1.725546e+38

In [40]:
# Export as CSV
final_df.to_csv("comparison.csv", index=False)